version: '3'
services:
    mongodb:
        image: mongo
        container_name: my-mongodb
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongostar
            MONGO_INITDB_ROOT_PASSWORD: starmongo
        volumes:
            - mongodb_data:/data/db
volumes:
    mongodb_data:
